### ISSUE TITLE
Eslint v7

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol#163]
See  
- https://github.com/airbnb/javascript/issues/2223
- https://github.com/airbnb/javascript/commit/5b462a04cdfebba712a3df18926edfcb4103d2a9#diff-8279b45a683d362b9fb4c42a35a6396c

**Comment by chentsulin** [comment]
https://github.com/airbnb/javascript/issues/2245
https://github.com/eslint/eslint/issues/13427

**Comment by tw0517tw** [comment]
https://github.com/eslint/eslint/issues/13427#issuecomment-647761976
eslint 7.3 update

**Comment by chentsulin** [comment]
The issue is fixed now, so I'm going to close this.
