### ISSUE TITLE
[Proposal] PropTypes order

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol#30]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-prop-types.md

這樣？

```
"react/sort-prop-types": ["error", {
  "callbacksLast": true,
  "ignoreCase": false,
  "requiredFirst": true,
}]
```

**Comment by tw0517tw** [comment]
原來有規則 是剛剛我用 order 沒搜尋到XD

**Comment by chentsulin** [comment]
requiredFirst 我決定改成 false

不然因為變成 required 就要搬順序感覺麻煩
