### ISSUE TITLE
[Proposal] no-else-return: 0

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol#5]

**Comment by tw0517tw** [comment]
我覺得改不改都可以

**Comment by chentsulin** [comment]
最近 airbnb 到 8.0 了 多了 import 跟 a11y 我是覺得不賴

**Comment by chentsulin** [comment]
我只是發現很多人都覺得有 else 可讀性比較好

**Comment by tw0517tw** [comment]
我也覺得頭腦負擔比較低
但是這個 rule 他寫的理由我也可以接受 所以我都可以

**Comment by zeldalink0515** [comment]
後端在 controller 寫一堆檢查的時候遵守這條 rule 會乾淨很多，但我現在覺得那是 MVC 本身的問題 :/

**Comment by chentsulin** [comment]
我本身對這個也是 +-0

@kpman 覺得呢？
