### ISSUE TITLE
[Proposal]: 'react/no-deprecated': [1, { 'react': '15.0.0' }],

### ISSUE THREAD

**Issue by chentsulin** [Yoctol/eslint-config-yoctol#8]
我們要統一使用 15 嗎？

```
'react/no-deprecated': [1, { 'react': '0.14.0' }],
```

react-native 也開始使用 15

https://github.com/facebook/react-native/blob/master/package.json#L127

**Comment by tw0517tw** [comment]
這是會把給定版本的舊寫法標成 warning?

**Comment by chentsulin** [comment]
嗯

**Comment by chentsulin** [comment]
看起來要 react-native v0.26 才能用 react v15

目前 v0.25 有命名碰撞問題
This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: createReactNativeComponentClass
  Paths: /Users/chentsulin/Projects/react-native-counter-ios-android/node_modules/react/lib/createReactNativeComponentClass.js collides with /Users/chentsulin/Projects/react-native-counter-ios-android/node_modules/react-native/Libraries/ReactNative/createReactNativeComponentClass.js

**Comment by tw0517tw** [comment]
但如果我們現在沒有要用 react-native 0.25 就暫時沒問題?
